___

<a href='https://mainacademy.ua/'> <img src='https://mainacademy.ua/wp-content/uploads/2019/03/logo-main.png' alt = 'Хмм, щось з інтернетом'/></a>
___

# Module 5: Data analysis with NumPy and Pandas

## Lab work 5.1



#### Мета: 

* навчитися працювати із бібліотекою NumPy в Python

### Завдання:

In [2]:
import numpy as np

Вивести версію та конфігурацію бібліотеки:

In [2]:
np.show_config()
print ('Версія:', np.__version__)

blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/User/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/User/anaconda3\\Library\\include']
Версія: 1.20.1


Створити вектор з 10 елементів, заповнений одиницями:

In [3]:
V = np.ones(10)
print(V)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Створити вектор із значеннями від 0 до 10:

In [4]:
V = np.arange(11)
print(V)

[ 0  1  2  3  4  5  6  7  8  9 10]


Створити матрицю 5 на 5, заповнену нулями:

In [5]:
V = np.zeros((5,5))
print(V)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Заповнити вектор з 20 елементів випадковими цілими числами. Знайти індекси ненульових елементів:

In [7]:
V = np.random.randint(0,100,20)
nz = np.nonzero(V)
print(V)
print(nz)

[97  0 38 27 24 88 81 15 96 13 44 48 78 61 91  7 33 56  6  9]
(array([ 0,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19], dtype=int64),)


Для вектора із попередньої задачі знайти середнє значення, медіану, стандартне відхилення:

In [7]:
mean = np.mean(V)
median = np.median(V)
std = np.std(V)
print('Середнє:', mean, 'Медіана:', median, 'Відхилення:', std)

Середнє: 51.666666666666664 Медіана: 54.0 Відхилення: 28.887851019207652


Створити дві матриці випадкових чисел розміром 4х2 та 2х2. Перемножити їх:

In [8]:
Vr = np.dot(np.random.rand(4,2), np.random.rand(2,2))

print(Vr)

[[0.05438147 0.54589826]
 [0.09768674 0.94818512]
 [0.06612576 0.67136207]
 [0.01341155 0.30496032]]


Результуючу матрицю із попередньої задачі перетворити у вектор. Знайти мінімальне та максимальне значення. 

Максимальне значення замінити на 0:

In [9]:
V = Vr.ravel()
Vmax, Vmin = V.max(), V.min()
V[V.argmax()] = 0
print(V)
print(Vmax, Vmin)

[0.05438147 0.54589826 0.09768674 0.         0.06612576 0.67136207
 0.01341155 0.30496032]
0.9481851220192166 0.013411551796827655


Знайдіть кореляцію першого рядка матриці із попереднього завдання із іншими рядками:

In [10]:
l1 = Vr[0]
l2 =Vr[1]
l3 = Vr[2]
l4 = Vr[3]
coorelation1 = np.corrcoef (l1, l2)
coorelation2 = np.corrcoef (l1, l3)
coorelation3 = np.corrcoef (l1, l4)
coorelation = np.corrcoef (Vr)
print(coorelation1)
print(coorelation2)
print(coorelation3)
print(coorelation)

[[ 1. -1.]
 [-1.  1.]]
[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
[[ 1. -1.  1.  1.]
 [-1.  1. -1. -1.]
 [ 1. -1.  1.  1.]
 [ 1. -1.  1.  1.]]


Дано матрицю. Знайти ранг матриці:

In [11]:
a = np.array([[ 1,  4, 5],
              [7, 3, 2],
              [9, 16, 1]])
rank = np.linalg.matrix_rank(a)
print(rank)

3


Знайти визначник матриці:

In [12]:
det = np.linalg.det(a)
print(det)

440.0000000000002


Знайти власні значення та власні вектори матриці: 

In [13]:
e_vals, e_vec = np.linalg.eigh(a)
print('Власні значення:', e_vals)
print('Власні вектори:', e_vec)

Власні значення: [-14.30540864  -4.34740072  23.65280936]
Власні вектори: [[ 0.15315575  0.88160309  0.44645191]
 [ 0.63674998 -0.43353159  0.6376518 ]
 [-0.75570681 -0.18661821  0.62775861]]


Знайдіть число, що найчастіше зустрічається в масиві:

In [16]:
a = np.random.randint(0,10,50)
print(np.bincount(a).argmax())

7


Виведіть лише парні числа, що діляться на 5:

In [17]:
a = np.random.randint(0,10,50)
 
print(a)
print((a[a % 2 == 0])[a[a % 2 == 0] % 5 == 0])

[3 0 8 7 9 5 4 5 0 3 9 8 4 9 4 1 8 7 8 6 7 0 8 4 7 1 2 2 6 8 8 8 1 9 8 8 8
 0 4 7 0 8 3 5 8 1 5 4 4 2]
[0 0 0 0 0]


Розв'яжіть систему рівнянь:
$$2x + 5y = 1 $$

$$x - 10y = 3  $$
   

In [18]:
M = np.array([[2., 5.], [1., -10.]]) 
v = np.array([1., 3.])
print('x,y=', np.linalg.solve(M, v))

x,y= [ 1.  -0.2]
